# for i in range(3):
#     print(i)
# i=0
# while(i<=3):
#     print(i)
#     i=i+1 #
# print("Done with the loop") #ideally we dont use while loop with numbers. Complex condtion er jonno while loop use kora hoy.


# # i=int(input("Enter the number: "))
# # while(i<=10):
# #     i=int(input("Enter the number: "))
# #     print(i)
# # print("Done with the loop")

# #ecrementing loop
count=5
k=1
while(count>0):
    print(count)
    count=count-1
while(k<=count):
        print("iteration: ",k)
        k=k+1
print("Decrementing loop done")